# fly.toml app configuration file generated for competitor-price-watcher on 2025-01-10T16:43:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "competitor-price-watcher"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "60s"
  method = "GET"
  timeout = "30s"
  path = "/docs"

[[vm]]
  cpu_kind = "shared"
  cpus = 8
  memory_mb = 4096
