# fly.toml app configuration file generated for competitor-price-watcher-test on 2025-03-18T14:47:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'competitor-price-watcher-test'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENV = 'test'
  PORT = '8080'

[[mounts]]
  source = 'cpw_test_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/docs'

[[vm]]
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
