"""Initial migration

Revision ID: 1a1c9db4c275
Revises: 
Create Date: 2025-02-19 09:31:21.843796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1c9db4c275'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_configs_country_code'), 'country_configs', ['country_code'], unique=True)
    op.create_index(op.f('ix_country_configs_id'), 'country_configs', ['id'], unique=False)
    op.create_table('domain_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_configs_domain'), 'domain_configs', ['domain'], unique=True)
    op.create_index(op.f('ix_domain_configs_id'), 'domain_configs', ['id'], unique=False)
    op.create_table('package_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_configs_id'), 'package_configs', ['id'], unique=False)
    op.create_index(op.f('ix_package_configs_package_id'), 'package_configs', ['package_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_configs_package_id'), table_name='package_configs')
    op.drop_index(op.f('ix_package_configs_id'), table_name='package_configs')
    op.drop_table('package_configs')
    op.drop_index(op.f('ix_domain_configs_id'), table_name='domain_configs')
    op.drop_index(op.f('ix_domain_configs_domain'), table_name='domain_configs')
    op.drop_table('domain_configs')
    op.drop_index(op.f('ix_country_configs_id'), table_name='country_configs')
    op.drop_index(op.f('ix_country_configs_country_code'), table_name='country_configs')
    op.drop_table('country_configs')
    # ### end Alembic commands ###
