"""Add config versions table

Revision ID: 53c9e244f1cd
Revises: 1a1c9db4c275
Create Date: 2025-02-21 09:17:13.000632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c9e244f1cd'
down_revision: Union[str, None] = '1a1c9db4c275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_type', sa.String(), nullable=True),
    sa.Column('config_id', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_versions_type_id_version', 'config_versions', ['config_type', 'config_id', 'version'], unique=False)
    op.create_index(op.f('ix_config_versions_id'), 'config_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_versions_id'), table_name='config_versions')
    op.drop_index('idx_config_versions_type_id_version', table_name='config_versions')
    op.drop_table('config_versions')
    # ### end Alembic commands ###
